project_id = "uqsbybajgrdbbjuauobi"

[functions.chat]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = true

[functions.generate-xlsx]
verify_jwt = true